# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS  = interfaces.hpp
SOURCES  = main.cpp
 symbian {
     LIBS           = -lBasicSave.lib
 } else {
     LIBS           = -L$${QT_BUILD_TREE}/plugins -lBasicSave
 }

 if(!debug_and_release|build_pass):CONFIG(debug, debug|release) {
    mac:LIBS = $$member(LIBS, 0) $$member(LIBS, 1)_debug
    win32:LIBS = $$member(LIBS, 0) $$member(LIBS, 1)d
 }
TEMPLATE = app
TARGET = QtPlugin
DESTDIR = ../
CONFIG += debug console
DEFINES += QT_LARGEFILE_SUPPORT
INCLUDEPATH += ./GeneratedFiles/Debug
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(QtPlugin.pri)
