# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./Interfaces.hpp
SOURCES += ./main.cpp
