# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./echoplugin.h
SOURCES += ./echoplugin.cpp
