# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./echowindow.h \
    ./echointerface.h
SOURCES += ./main.cpp \
    ./echowindow.cpp
FORMS += ./echowindow.ui
RESOURCES += echowindow.qrc
