# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./Model.hpp \
    ./Reader.hpp \
    ./Serializable.hpp \
    ./TabReader.hpp \
    ./TabWriter.hpp \
    ./Writer.hpp \
    ./XmlTxtWriter.hpp \
    ./XmlTxtReader.hpp \
    ./XmlStructureParser.hpp
SOURCES += ./main.cpp \
    ./Model.cpp \
    ./TabReader.cpp \
    ./TabWriter.cpp \
    ./XmlTxtWriter.cpp \
    ./XmlTxtReader.cpp \
    ./XmlStructureParser.cpp
